export const currencyList = [
    {
        value: "USD",
        label: "USD",
        details: {
            country: "United States",
            currencySymbol: "$",
            currencyName: "United States Dollar",
            currencyShortForm: "USD",
            currencyColor: "#FF6B6B",
        },
    },
    {
        value: "EUR",
        label: "EUR",
        details: {
            country: "European Union",
            currencySymbol: "€",
            currencyName: "Euro",
            currencyShortForm: "EUR",
            currencyColor: "#4CAF50",
        },
    },
    {
        value: "GBP",
        label: "GBP",
        details: {
            country: "United Kingdom",
            currencySymbol: "£",
            currencyName: "British Pound Sterling",
            currencyShortForm: "GBP",
            currencyColor: "#2196F3",
        },
    },
    {
        value: "JPY",
        label: "JPY",
        details: {
            country: "Japan",
            currencySymbol: "¥",
            currencyName: "Japanese Yen",
            currencyShortForm: "JPY",
            currencyColor: "#9C27B0",
        },
    },
    {
        value: "INR",
        label: "INR",
        details: {
            country: "India",
            currencySymbol: "₹",
            currencyName: "Indian Rupee",
            currencyShortForm: "INR",
            currencyColor: "#FFC107",
        },
    },
    {
        value: "KRW",
        label: "KRW",
        details: {
            country: "South Korea",
            currencySymbol: "₩",
            currencyName: "South Korean Won",
            currencyShortForm: "KRW",
            currencyColor: "#673AB7",
        },
    },
    {
        value: "ILS",
        label: "ILS",
        details: {
            country: "Israel",
            currencySymbol: "₪",
            currencyName: "Israeli Shekel",
            currencyShortForm: "ILS",
            currencyColor: "#795548",
        },
    },
    {
        value: "VND",
        label: "VND",
        details: {
            country: "Vietnam",
            currencySymbol: "₫",
            currencyName: "Vietnamese Dong",
            currencyShortForm: "VND",
            currencyColor: "#8BC34A",
        },
    },
    {
        value: "BDT",
        label: "BDT",
        details: {
            country: "Bangladesh",
            currencySymbol: "৳",
            currencyName: "Bangladeshi Taka",
            currencyShortForm: "BDT",
            currencyColor: "#F44336",
        },
    },
    {
        value: "RUB",
        label: "RUB",
        details: {
            country: "Russia",
            currencySymbol: "₽",
            currencyName: "Russian Ruble",
            currencyShortForm: "RUB",
            currencyColor: "#607D8B",
        },
    },
    {
        value: "BRL",
        label: "BRL",
        details: {
            country: "Brazil",
            currencySymbol: "R$",
            currencyName: "Brazilian Real",
            currencyShortForm: "BRL",
            currencyColor: "#FF9800",
        },
    },
    {
        value: "UAH",
        label: "UAH",
        details: {
            country: "Ukraine",
            currencySymbol: "₴",
            currencyName: "Ukrainian Hryvnia",
            currencyShortForm: "UAH",
            currencyColor: "#03A9F4",
        },
    },
    {
        value: "KZT",
        label: "KZT",
        details: {
            country: "Kazakhstan",
            currencySymbol: "₸",
            currencyName: "Kazakhstani Tenge",
            currencyShortForm: "KZT",
            currencyColor: "#9E9E9E",
        },
    },
    {
        value: "TWD",
        label: "TWD",
        details: {
            country: "Taiwan",
            currencySymbol: "₪",
            currencyName: "New Taiwan Dollar",
            currencyShortForm: "TWD",
            currencyColor: "#00BCD4",
        },
    },
];
